#personal_profile
print("------personal_profile------")
name=input("enter your name \n")
age=int(input("enter your age \n"))
faculty=input(" you are faculty in?? \n")
learning=input("what languge are you learning \n")
goal=input("what is your goal \n")
print("------personal_profile------")
print(f"Name:{name} ")
print(f"Age:{age} ") 
print(f"Faculty:{faculty} ")
print(f"Learning:{learning} ")
print(f"Goal:{goal} ")
print("-----------------------------")
